endpoint.savings-account.url=http://host.docker.internal:3001/api/proxy/v1.0/prometeus/savings-account
endpoint.current-account.url=http://host.docker.internal:3001/api/proxy/v1.0/prometeus/current-account
endpoint.party-data.url=http://host.docker.internal:3001/api/proxy/v1.0/prometeus/party-lifecycle-management
endpoint.connect.timeout=3000
endpoint.socket.timeout=5000
camel.rest.component=platform-http
camel.rest.port=8080
camel.rest.binding-mode=off
quarkus.package.jar.type=uber-jar
quarkus.package.jar.add-runner-suffix=false
