endpoint.savings-account.url=${ENDPOINT_SAVINGS_ACCOUNT_URL}
endpoint.current-account.url=${ENDPOINT_CURRENT_ACCOUNT_URL}
endpoint.party-data.url=${ENDPOINT_PARTY_DATA_URL}
endpoint.connect.timeout=${ENDPOINT_CONNECT_TIMEOUT:3000}
endpoint.socket.timeout=${ENDPOINT_SOCKET_TIMEOUT:5000}
camel.rest.component=platform-http
camel.rest.port=8080
camel.rest.binding-mode=off

# Compilar JVM
quarkus.package.jar.type=uber-jar
quarkus.package.jar.add-runner-suffix=false

# Compilar Nativo
# quarkus.native.resources.includes=camel/**
